# Generated by Django 4.1.3 on 2023-08-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_hardskills_softskills_techstack'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
