# Generated by Django 4.1.3 on 2023-08-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_portfolio_portfolio_url_portfolio_tech_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('starting_date', models.CharField(blank=True, max_length=200, null=True)),
                ('ending_date', models.CharField(blank=True, max_length=200, null=True)),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
