# Generated by Django 4.1.3 on 2023-08-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_membershipcertificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.RemoveField(
            model_name='social',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='social',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='social',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='social',
            name='phone2',
        ),
        migrations.AddField(
            model_name='contact',
            name='email2',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
