# Generated by Django 4.1.3 on 2023-08-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='job_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
