# Generated by Django 4.1.3 on 2023-08-27 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_alter_professionalexperience_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalexperience',
            name='job_description',
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.professionalexperience')),
            ],
        ),
    ]
