# Generated by Django 4.1.3 on 2023-08-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0012_remove_professionalexperience_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='ending_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
