# Generated by Django 4.1.3 on 2023-08-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0013_alter_professionalexperience_ending_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
