# Generated by Django 4.1.3 on 2023-08-27 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0015_jobdescription_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='job_description',
            new_name='job_title',
        ),
    ]
