# Generated by Django 4.1.3 on 2023-08-27 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0016_rename_job_description_jobdescription_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='job_title',
            new_name='experience',
        ),
    ]
