# Generated by Django 3.0.5 on 2023-09-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0018_auto_20230907_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caption',
            old_name='screen_shot',
            new_name='caption_shots',
        ),
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='year_acquired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_cover'),
        ),
    ]
