# Generated by Django 3.0.5 on 2023-09-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0019_auto_20230908_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Not Completed', 'Not Completed')], max_length=100, null=True),
        ),
    ]
