# Generated by Django 3.0.5 on 2023-09-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0020_portfolio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='deployment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
