# Generated by Django 3.0.5 on 2023-09-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0021_portfolio_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='caption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='captions'),
        ),
    ]
