# Generated by Django 3.0.5 on 2023-09-10 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0022_caption_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipcertificate',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.Membership'),
        ),
    ]
