# Generated by Django 3.0.5 on 2023-09-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0023_membershipcertificate_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipcertificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memberships'),
        ),
    ]
